#!/usr/bin/env bash

#
# requires:
#  1. docker login
#  2. docker buildx create --name multiarch --use
#
version="$(cargo pkgid | grep -oP '\d+\.\d+\.\d+')"
platforms=(
  "linux/amd64"
  "linux/arm64"
  "linux/arm/v7"
)

docker buildx build \
  --platform "$(echo "${platforms[*]}" | tr ' ' ',')" \
  -t szaffarano/korrosync:latest \
  -t szaffarano/korrosync:v"$version" \
  --push .
